// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAETMXhTtxTzR26e4ZZAvCxNBIyoThr4MM',
    appId: '1:261478912153:web:352eaeb163fdf2ff9b6808',
    messagingSenderId: '261478912153',
    projectId: 'tiktok-clone-66b91',
    authDomain: 'tiktok-clone-66b91.firebaseapp.com',
    storageBucket: 'tiktok-clone-66b91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8feCFh9blT6W_HAgBAxvq8mOLRmREtm0',
    appId: '1:261478912153:android:78840fcb828f27aa9b6808',
    messagingSenderId: '261478912153',
    projectId: 'tiktok-clone-66b91',
    storageBucket: 'tiktok-clone-66b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6G4DZK2O9gompOrj1h7ZwGKZ6DShAYLg',
    appId: '1:261478912153:ios:174d51c12456c6009b6808',
    messagingSenderId: '261478912153',
    projectId: 'tiktok-clone-66b91',
    storageBucket: 'tiktok-clone-66b91.appspot.com',
    iosClientId: '261478912153-n5bucanbdgt85iknck717nu55sn1gkrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokWithoutCringe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6G4DZK2O9gompOrj1h7ZwGKZ6DShAYLg',
    appId: '1:261478912153:ios:38992658085dd63f9b6808',
    messagingSenderId: '261478912153',
    projectId: 'tiktok-clone-66b91',
    storageBucket: 'tiktok-clone-66b91.appspot.com',
    iosClientId: '261478912153-jdksnah0c2kc4pg1r2q7hqjsi09ck75k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokWithoutCringe.RunnerTests',
  );
}
